site_name: kkdev docs
site_url: https://black-tree-04b1db300.6.azurestaticapps.net/
site_description: ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆç½®ãå ´
site_author: kkdev

repo_url: https://github.com/kkdev92/Portfolio
repo_name: kkdev92/Portfolio

copyright: Copyright &copy; 2025 kkdev

theme:
  feature:
    tabs: true
  language: ja
  name: material
  logo: img/logo.jpg

extra_javascript:
  - assets/js/auth.js

markdown_extensions:
  - admonition  # ãƒ’ãƒ³ãƒˆãƒ»æ³¨æ„ãƒ»è­¦å‘Šãªã©ã®ã‚¹ã‚¿ã‚¤ãƒ«ä»˜ããƒ–ãƒ­ãƒƒã‚¯ã‚’ä½œæˆ
  - attr_list   # Markdown è¦ç´ ã«ã‚¯ãƒ©ã‚¹ã‚„IDãªã©ã®å±æ€§ã‚’ä»˜ä¸ã§ãã‚‹ï¼ˆä¾‹: {: .my-class }ï¼‰
  - codehilite  # ã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯ã«ã‚·ãƒ³ã‚¿ãƒƒã‚¯ã‚¹ãƒã‚¤ãƒ©ã‚¤ãƒˆã‚’é©ç”¨
  - footnotes   # è„šæ³¨ã‚’ä½¿ãˆã‚‹ã‚ˆã†ã«ã™ã‚‹ï¼ˆ[^1] ãªã©ï¼‰
  - pymdownx.keys       # ã‚­ãƒ¼å…¥åŠ›é¢¨ã®è¡¨è¨˜ï¼ˆä¾‹: âŒ˜ Cmd + Cï¼‰ã‚’ä½¿ãˆã‚‹
  - pymdownx.magiclink  # URLã‚„@ãƒ¦ãƒ¼ã‚¶ãƒ¼åã€#issueç•ªå·ã‚’è‡ªå‹•ã§ãƒªãƒ³ã‚¯ã«å¤‰æ›
  - pymdownx.mark       # ãƒ†ã‚­ã‚¹ãƒˆã®ãƒã‚¤ãƒ©ã‚¤ãƒˆï¼ˆãƒãƒ¼ã‚«ãƒ¼é¢¨ã®è£…é£¾ï¼‰ã‚’è¿½åŠ 
  - pymdownx.superfences  # é«˜åº¦ãªã‚³ãƒ¼ãƒ‰ãƒ–ãƒ­ãƒƒã‚¯è¨˜è¿°ãŒã§ãã‚‹ï¼ˆä»–ã®æ‹¡å¼µã¨ä½µç”¨ã—ã‚„ã™ã„ï¼‰
  - pymdownx.tilde      # ~~æ‰“ã¡æ¶ˆã—ç·š~~ ã‚„ ~å°æ–‡å­—~ ã®è¨˜æ³•ã‚’è¿½åŠ 
  - pymdownx.tasklist: # ã‚¿ã‚¹ã‚¯ãƒªã‚¹ãƒˆï¼ˆãƒã‚§ãƒƒã‚¯ãƒªã‚¹ãƒˆï¼‰ã‚’ä½œæˆ
      custom_checkbox: true
  - toc:
      permalink: true   # å„è¦‹å‡ºã—ã«ãƒ‘ãƒ¼ãƒãƒªãƒ³ã‚¯ï¼ˆğŸ”—ï¼‰ã‚’è¡¨ç¤ºã—ã€ãƒªãƒ³ã‚¯å¯èƒ½ã«ã™ã‚‹
